### ISSUE TITLE
Doesn't work in Mail 10.1

### ISSUE THREAD

**Issue by ajkblue** [scr34m/MailReceipt#1]

**Comment by scr34m** [comment]
New pkg uploaded to work with latest Mail.app and also sourcecode too

**Comment by ajkblue** [comment]
@scr34m It does install correctly now, but how exactly does this work? Am I supposed to receive a notification that the email was read and delivered correctly?

**Comment by scr34m** [comment]
When you write a new letter then two new button shows up "R" and "D", letters stands for Reading and Delivery receipt.

If the recipient uses Mail.app then you wont get a reply because Apple email client does not support it, but other e-mail clients ex. Outlook, Thunderbird will ask the reader to send back response about email reading.

Delivery receipt sent by SMTP servers when message arrived, this does not mean that the recipient red, just successfully delivered to inbox.

**Comment by ajkblue** [comment]
@scr34m Ah, okay I understand how it works now
