### ISSUE TITLE
How do we know if it has worked

### ISSUE THREAD

**Issue by demetre19** [scr34m/MailReceipt#7]
I just installed your add on, and sent an email to gmail.

I am not sure if it has worked will we receive a notification somewhere?

Thanks

**Comment by scr34m** [comment]
Unfortunately gmail is not good, because not asking the recipient about read and not sending back delivery notification as i tested.

You can test with roundcube, horde webmails or an outlook user, because those applications asking the user about read to send back a notification, delivery notification works with postfix smtp server, but not with exim smtp it is not supporting delivery notification.
